### ISSUE TITLE
Add Support for tag prefixes that contain '-'

### ISSUE THREAD

**Issue by Michriko** [JenWa/changelog-creator#22]
Tags containing '-' are considered as release candidates even if the '-' is in the prefix.

Please add support for prefixes containing a '-'

**Comment by JenWa** [comment]
Will be fixed with this card: https://github.com/JenWa/changelog-creator/projects/1#card-64139091

**Comment by JenWa** [comment]
It's now possible to define a prerelease-id upon which a pre-release is detected.
The only issue now could be that the pre-id has the same value as the prefix (But I don't see that coming).
+ it's currently only possible to define one prerelease-id and one prefix.
I will probably add a feature to define multiple pre-ids and prefixes
